torch_weights: ./checkpoints/goliath/sapiens_0.3b/sapiens_0.3b_goliath_best_goliath_AP_573.pth
formats:
  - torchscript
  - onnx
  - tensorrt
enable_mixed_precision: true
input_shape: [1024, 768]
device: cuda:0
repeats: 1000
enable_benchmark: false
enable_visualization: true

executor:
  module: src.export.executor
  cls: SapiensExecutor
exporter:
  module: src.export.exporter
  cls: SapiensExporter

tensorrt:
  specific:
    log_level: INFO
    precision: fp16
    profile_shapes:
      - min: [1, 3, 1024, 768]
        opt: [4, 3, 1024, 768]
        max: [8, 3, 1024, 768]
    workspace: 1_073_741_824
    flags:
      - TF32
      - DIRECT_IO
      - PREFER_PRECISION_CONSTRAINTS
      - SPARSE_WEIGHTS
    profiling_verbosity: NONE
    max_aux_streams: 4
    runtime_platform: null
    compatibility_level: null
    tactics: null
    algorithm: ENTROPY_CALIBRATION_2
  enable_timing_cache: true
  enable_calibration_cache: true
  output_file: checkpoints/tensorrt/model.plan
  force_rebuild: true

onnx:
  specific:
    keep_initializers_as_inputs: false
    export_params: true
    verbose: null
    input_names: [input]
    output_names: [heatmap]
    opset_version: 17
    dynamic_axes: null
    training: EVAL
    do_constant_folding: true
  simplify: true
  output_file: checkpoints/onnx/model.onnx
  force_rebuild: true

torchscript:
  optimize: false
  output_file: checkpoints/torchscript/model.pt
  force_rebuild: true

openvino:
  precision: fp16
  output_file: checkpoints/openvino/model.xml
  force_rebuild: true
  input_names:
    - images
  device: CPU
